// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB45WOMCCd_x3vy0WS9HWvqtnbPY2apOg',
    appId: '1:171539755117:web:5fbf3c7cfa958a796fcf64',
    messagingSenderId: '171539755117',
    projectId: 'discoverrwanda',
    authDomain: 'discoverrwanda.firebaseapp.com',
    storageBucket: 'discoverrwanda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefsQtYC7Mh0xL9_E87Xy6iiZ78iVFano',
    appId: '1:171539755117:android:832be6e91c5ab0c06fcf64',
    messagingSenderId: '171539755117',
    projectId: 'discoverrwanda',
    storageBucket: 'discoverrwanda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUwFD3JRhy6Jy62Bfx5XS4WtWb01hyd_A',
    appId: '1:171539755117:ios:8206f0f46cddf0666fcf64',
    messagingSenderId: '171539755117',
    projectId: 'discoverrwanda',
    storageBucket: 'discoverrwanda.appspot.com',
    iosBundleId: 'com.example.rwandapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUwFD3JRhy6Jy62Bfx5XS4WtWb01hyd_A',
    appId: '1:171539755117:ios:8206f0f46cddf0666fcf64',
    messagingSenderId: '171539755117',
    projectId: 'discoverrwanda',
    storageBucket: 'discoverrwanda.appspot.com',
    iosBundleId: 'com.example.rwandapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB45WOMCCd_x3vy0WS9HWvqtnbPY2apOg',
    appId: '1:171539755117:web:596ae60170b3c31c6fcf64',
    messagingSenderId: '171539755117',
    projectId: 'discoverrwanda',
    authDomain: 'discoverrwanda.firebaseapp.com',
    storageBucket: 'discoverrwanda.appspot.com',
  );
}
