// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl4nFMI7HBO-KFYCO8GucIWHOVX_yPkTM',
    appId: '1:598862053835:web:5d2928e9b2892b4b6e364e',
    messagingSenderId: '598862053835',
    projectId: 'discover-rwanda',
    authDomain: 'discover-rwanda.firebaseapp.com',
    databaseURL: 'https://discover-rwanda-default-rtdb.firebaseio.com',
    storageBucket: 'discover-rwanda.appspot.com',
    measurementId: 'G-ZNZD4RRL96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDggL_nu7X50bHxuIRONH5Zu5RVLoAPqgc',
    appId: '1:598862053835:android:44538eb8ea4c39a06e364e',
    messagingSenderId: '598862053835',
    projectId: 'discover-rwanda',
    databaseURL: 'https://discover-rwanda-default-rtdb.firebaseio.com',
    storageBucket: 'discover-rwanda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZTk_p3XCkcnrT_n-y4PQ3InakfesXxvA',
    appId: '1:598862053835:ios:8ba9c363253ed7976e364e',
    messagingSenderId: '598862053835',
    projectId: 'discover-rwanda',
    databaseURL: 'https://discover-rwanda-default-rtdb.firebaseio.com',
    storageBucket: 'discover-rwanda.appspot.com',
    iosBundleId: 'com.example.implementation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZTk_p3XCkcnrT_n-y4PQ3InakfesXxvA',
    appId: '1:598862053835:ios:8ba9c363253ed7976e364e',
    messagingSenderId: '598862053835',
    projectId: 'discover-rwanda',
    databaseURL: 'https://discover-rwanda-default-rtdb.firebaseio.com',
    storageBucket: 'discover-rwanda.appspot.com',
    iosBundleId: 'com.example.implementation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl4nFMI7HBO-KFYCO8GucIWHOVX_yPkTM',
    appId: '1:598862053835:web:67105ab52addbc6c6e364e',
    messagingSenderId: '598862053835',
    projectId: 'discover-rwanda',
    authDomain: 'discover-rwanda.firebaseapp.com',
    databaseURL: 'https://discover-rwanda-default-rtdb.firebaseio.com',
    storageBucket: 'discover-rwanda.appspot.com',
    measurementId: 'G-P4CB9EV9QR',
  );
}


